openapi: 3.1.0
info:
  title: Showtime API
  description: This is the API of the Showtime service
  contact:
    email: helene.coullon@imt-atlantique.fr
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: developers
  description: Operations available to regular developers
paths:
  /:
    get:
      tags:
      - developers
      summary: home page of the service
      operationId: home
      responses:
        "200":
          description: welcome message
          content:
            text/html:
              schema:
                type: string
                example: <h1 style='color:blue'>Welcome to the Showtime service!</h1>
  /showtimes:
    get:
      tags:
      - developers
      summary: get the full JSON database
      operationId: get_schedule
      responses:
        "200":
          description: full JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllSchedule'
    post:
      tags:
      - developers
      summary: create a new showtime
      operationId: create_showtime
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
      responses:
        "200":
          description: new showtime created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: schedule already exists for that date
  /showtimes/{date}:
    put:
      tags:
      - developers
      summary: update an existing showtime by date
      operationId: update_showtime
      parameters:
      - name: date
        in: path
        description: date.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Schedule'
      responses:
        "200":
          description: showtime updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: no schedule found on that date
    delete:
      tags:
      - developers
      summary: delete an existing showtime by date
      operationId: delete_showtime
      parameters:
      - name: date
        in: path
        description: date.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: showtime deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: no schedule found on that date
    get:
      tags:
      - developers
      summary: get details of a showtime by date
      operationId: get_showtime_bydate
      parameters:
      - name: date
        in: path
        description: date.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: showtime details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Schedule'
        "400":
          description: no movie scheduled at this date
components:
  schemas:
    AllSchedule:
      required:
      - schedule
      type: object
      properties:
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/Schedule'
    Schedule:
      required:
      - date
      - movies
      type: object
      properties:
        date:
          type: string
          example: "20151130"
        movies:
          type: array
          items:
            type: string
            example: 720d006c-3a57-4b6a-b18f-9b713b073f3c
